name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Triggered when code is pushed to the main branch
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your code from GitHub to the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to your Docker Hub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

          # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/product-catalog # Replace with your image name

      # Step 3: Set up Docker Buildx (for advanced build features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build the image and push it to Docker Hub
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          # Use the Dockerfile in the current directory
          file: ./Dockerfile 
          push: true
          # Tags the image with 'latest' and the specific commit SHA
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:${{ github.sha }}